### ISSUE TITLE
0 task Checklist

### ISSUE THREAD

**Issue by rafalgorniak** [rafalgorniak/Programming-Technology#1]
# Repository check list

- [x] the task provides required feedback and has been submitted (needs grading)
- [x] the ability to clone the repository to the teacher's computer
- [x] README.md contains required information
- [x] build succeeded
- [x] all UT's are green
