### ISSUE TITLE
2 task Checklist

### ISSUE THREAD

**Issue by rafalgorniak** [rafalgorniak/Programming-Technology#3]
- [x] text is in C# and use .NET
- [x] build succeeded
- [x] all UT are green
- [x] Object model representing process data (reuse it from Task1)
- [x] layers are clearly stated in the language terms
- [x] `Data` layer is implemented using external SQL database and should be defined using LINQ to SQL (ORM)
- [x] LINQ (method and query syntax) is used to fetch data from the database
- [x] `Presentation` - his layer must be implemented in accordance with the `Model-View-ViewModel` (`MVVM`) software pattern
- [x] `Presentation` - the Master-Detail pattern
- [x] `View Model` must be tested using 2 independent `Model` data generation methods
- [x] `View Model` is tested independently
- [x] `View Model` use dependency injection for testing purpose (additional framework is not required)
- [x] The data and controls must be bond together using the data binding mechanism
- [x] `View` - design the appropriate GUI using `XAML` language (it should be C# codeless)
